service: API-SERVICE-TRADE

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  UserCreate:
    handler: lib/handlers/UserHandler.UserCreate
    events:
      - http:
          path: /
          method: post
          cors: true
